// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkg6MtD1yx_ilSYwdrn2uWjq9xi8k1KFg',
    appId: '1:331365296580:web:f34de4e514ef4dbf699c91',
    messagingSenderId: '331365296580',
    projectId: 'cuatro-application-6193f',
    authDomain: 'cuatro-application-6193f.firebaseapp.com',
    storageBucket: 'cuatro-application-6193f.appspot.com',
    measurementId: 'G-7E6VENHSMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6JvbFVNUA-j9TDsI0HOAvOcx538pKLFE',
    appId: '1:331365296580:android:f7271e208465cb72699c91',
    messagingSenderId: '331365296580',
    projectId: 'cuatro-application-6193f',
    storageBucket: 'cuatro-application-6193f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0stw_HLuwY6nVLG17UpMGNGSsLL7fMsg',
    appId: '1:331365296580:ios:bc1597b04494e4a9699c91',
    messagingSenderId: '331365296580',
    projectId: 'cuatro-application-6193f',
    storageBucket: 'cuatro-application-6193f.appspot.com',
    iosBundleId: 'com.example.cuatroApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0stw_HLuwY6nVLG17UpMGNGSsLL7fMsg',
    appId: '1:331365296580:ios:bc1597b04494e4a9699c91',
    messagingSenderId: '331365296580',
    projectId: 'cuatro-application-6193f',
    storageBucket: 'cuatro-application-6193f.appspot.com',
    iosBundleId: 'com.example.cuatroApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkg6MtD1yx_ilSYwdrn2uWjq9xi8k1KFg',
    appId: '1:331365296580:web:bdd4ba49c4f79bdc699c91',
    messagingSenderId: '331365296580',
    projectId: 'cuatro-application-6193f',
    authDomain: 'cuatro-application-6193f.firebaseapp.com',
    storageBucket: 'cuatro-application-6193f.appspot.com',
    measurementId: 'G-C779ZLPRTH',
  );
}
